# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Site settings
title: anyisland.com 
email: anyislandcreative@gmail.com
description: 
baseurl: ""
#url: "http://jeremybarkley.com"
#twitter_username: zombiestiltskin
#github_username:  sensoph1

# Build settings
markdown: kramdown
permalink: pretty

gems: [jekyll-paginate]

paginate: 10
<<<<<<< HEAD
theme: jekyll-theme-midnight
=======
=======
theme: jekyll-theme-time-machine
>>>>>>> 0cc7da761606e66d4867ab32ce45338fd3a35f1d
>>>>>>> be66c92d16fe7e1088b10c7a22570b9568c959bf
